add create subscription
Borodutch/paid_subscription_bot pull request #4
Opened 2021-07-12 22:44 UTC by fanamoner

2021-07-13 16:03 UTC, backmeupplz requested changes

2021-07-13 16:03 UTC, backmeupplz commented on .prettierrc.json
> +{
Возьми вот этот: https://github.com/Borodutch/frontend-starter-react/blob/main/.prettierrc.json

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +const Wallet = require('ethereumjs-wallet').default
Можем найти типы получше, чтобы не нужно было делать `require`? `Web3` нам тут разве будет недостаточно?

2021-07-13 16:03 UTC, backmeupplz commented on package.json
> +    "ethereumjs-wallet": "^1.0.1",
Попробуй со `web3` поработать

2021-07-13 16:03 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  return getOrCreateSubscription(ctx)
Тут в `startPayload` может прийти ID канала, на который человек пытается подписаться. Плюс, если нет языка, может начаться `sendLanguage`, куда тоже нужно закидывать startPayload — подписка после выбора языка сработает?

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  chatId: string
давай сделаем тут `number`

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  adress: string
`address`

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  adress: string
Давай, кстати, укажем именно `ethAddress` тут, или добавим прямо структуру-объект с разными способами оплаты? После ETH мы будем подключать другие криптовалюты.

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  payment: number
Давай создадим отдельную модель `Payment` и будем его сохранять в бд. У Payment будет поле `subscription: Ref<Subscription>`, обратная связь, вроде как, не нужна.

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  payment: number
А если это цена, то давай назовем это `price` :)

2021-07-13 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  payment: number
И мб `price` тоже будет структурой, ведь price может быть разным, в зависимости от типа оплаты (эфир, битки, т.д.)

2021-07-19 16:03 UTC, backmeupplz requested changes

2021-07-19 16:03 UTC, backmeupplz commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
А зачем нам эти изменения?

2021-07-19 16:03 UTC, backmeupplz commented on src/models/Price.ts
> +  @prop({ required: true, ref: 'Subscription' })
А можно тут сделать `ref: Subscription`? Чтобы убрать лишнюю магическую строку

2021-07-19 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +export async function getOrCreateSubscription(ctx: Context) {
Не передавай сюда Context, пожалуйста. У этой функции не должно быть сайд-эффектов, связанных с ТГ. Она должно получать или создавать подписку. Все, что нужно сделать с ТГ — делай вне этой функции.

2021-07-19 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  addresses: { ethAddress: string }
Давай у `addresses` и `privateKeys` укажем тип отдельным `interface` или `class`, чтобы не городить объект тут. Можно сделать этот интерфейс или класс прямо в этом файле, экспортить его не нужно.

2021-07-19 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +      `You already have a subscription.\nYour address is:${price.subscription.addresses.ethAddress}\nYour payment is: ${price.amount.ethAmount} ETH.`
Давай не различать, создана или найдена подписка. Постоянно просто говорить юзеру: для подписки на вот этот чат, вам нужно заплатить сюда вот столько.

2021-07-19 16:03 UTC, backmeupplz commented on src/models/Subscription.ts
> +  const priceCreated = await PriceModel.create({
Слабо понимаю связь Subscription и Price. Напиши в чате, пожалуйста, что именно ты под ними понимаешь.

Я думал, что у Subscription будет просто объект `prices` типа: `{ monthly: { eth: 0.005 } }`, указывающий, сколько стоит подписка в месяц.

2021-07-20 10:14 UTC, fanamoner commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
Для исправления ошибки `TypeError: web3_1.default is not a constructor` и возможности работы с модулем Web3. Решение проблемы взял [отсюда](https://github.com/ChainSafe/web3.js/issues/2486)

2021-07-21 16:22 UTC, backmeupplz requested changes

2021-07-21 16:22 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  const userId = ctx.from.id
Если ты их только один раз испольузешь после, можно не создавать лишних переменных, а сразу исопльзовать `ctx.from.id`, например

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +  options: { allowMixed: Severity.ALLOW },
Давай выставим этот флаг сразу всей монге, а не только этой модели

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +    return `To subscribe to this chat, you need to pay ${subscription.prices.monthly.eth} ETH to this adress: ${subscription.addresses.eth}.`
Выглядит так, как будто ты можешь из этой функции вернуть `subscription` и использовать его вне этой функции. Уж точно не надо возвращать строку :)

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +  const subscription = await SubscriptionModel.findOne({
Если сделаешь `let`, то потом сможешь не создавать `subscriptionCreated` переменную, а использовать эту

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +  const web3 = new Web3(Web3.givenProvider || 'ws://localhost:8545')
Давай вот это добавим в `.env` с записью в readme и `.env.sample`

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +  const web3 = new Web3(Web3.givenProvider || 'ws://localhost:8545')
Можем, кстати, web3 не создавать каждый раз, а создать один раз и экспортнуть, например, в `helpers/web3`? :)

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +  const subscriptionCreated = await SubscriptionModel.create({
Давай вместо этого использовать `new SubscriptionModel({ ... }).save()`

2021-07-21 16:22 UTC, backmeupplz commented on src/models/Subscription.ts
> +    prices: { monthly: { eth: price } },
Не нужно сразу создавать `price`, помнишь, нам нужно будет дать админу настроить цену в месяц?

2021-07-22 19:18 UTC, backmeupplz requested changes

2021-07-22 19:18 UTC, backmeupplz commented on src/models/Subscription.ts
> +  @prop({})
Не нужно писать `{}`, если нет настроек, ну и он, похоже, optional, так что укажи `prices?`

2021-07-22 19:18 UTC, backmeupplz commented on src/models/Subscription.ts
> +    addresses: {
Слушай, а мы можем как-то сюда прямо `ethAccount` сохранить? Или там не просто структура, а еще и методы у объекта `ethAccount`? Тип `Account` должен быть доступен в web3, вроде как

2021-07-22 19:18 UTC, backmeupplz commented on src/models/Chat.ts
> -  schemaOptions: { timestamps: true },
Зачем это убирать? Добавь таймстампы и в `Subscription`

2021-07-22 19:18 UTC, backmeupplz commented on .env.sample
> +WEB3_PROVIDER=http://localhost:27017
А это валидный URL для провайдера?

2021-07-22 19:18 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +    sendLanguage(MessageAfterLanguage.start, startPayload)(ctx)
Если у человека не установлен язык, нужно этот язык спросить — а после выбора языка отправить то, что хотели отправить тут.

2021-07-22 19:18 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +    const subscriptionInfo = await getOrCreateSubscription(
Это же не `subscriptionInfo`, а полноценный `subscription`

2021-07-22 19:18 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +    return ctx.reply(subscriptionInfo)
Отправлять пользователю голый json объект плохо, всегда отправляй сразу нормальные строки, прогоняя их через i18n.

2021-07-23 08:57 UTC, fanamoner commented on src/models/Chat.ts
> -  schemaOptions: { timestamps: true },
Я ведь выставил global options в typegoose. Все модели будут иметь `schemaOptions: { timestamps: true }`

2021-07-23 11:07 UTC, fanamoner commented on src/models/Subscription.ts
> +    addresses: {
Можно сохранить. `web3.eth.accounts.create()` возвращает объект с адресом, ключом и функциями `sign()` для транзакций. Источник: [документация Web3](https://web3js.readthedocs.io/en/v1.3.4/web3-eth-accounts.html#create)

2021-07-23 11:33 UTC, fanamoner commented on .env.sample
> +WEB3_PROVIDER=http://localhost:27017
Да. Если пользователь не хочет использовать third-party провайдеров (напр. Infura), он может сам создать свой node и подключить его к локалхосту. Источник: [stackexchange](https://ethereum.stackexchange.com/questions/84582/how-to-connect-ethereum-local-provider-https-localhost8545).

2021-07-23 11:44 UTC, fanamoner commented on src/models/Subscription.ts
> +    addresses: {
Функции `web3.eth.accounts.signTransaction`, `web3.eth.accounts.sign`,  `web3.eth.accounts.encrypt` существуют отдельно, поэтому их можно будет потом использовать

2021-07-23 16:43 UTC, backmeupplz requested changes

2021-07-23 16:43 UTC, backmeupplz commented on locales/en.yaml
> +subscription_message: In order to subscribe to this group, you need to transfer 1 ETH to ${subscriptionAddress}.
Количество ETH тоже нужно передавать сюда переменной, оно будет разное для разных подписок

2021-07-23 16:43 UTC, backmeupplz commented on locales/ru.yaml
> +subscription_message: Чтобы подписаться на этоу группу, вам нужно перевести 1 ETH по адресу ${subscriptionAddress}.
Давай опечатку в слове "этоу" поправим

2021-07-23 16:43 UTC, backmeupplz commented on src/models/Chat.ts
> -  schemaOptions: { timestamps: true },
Понял, спасибо!

2021-07-23 16:43 UTC, backmeupplz commented on src/models/Subscription.ts
> +setGlobalOptions({
Давай это уберем в `src/models/index.ts`

2021-07-23 16:43 UTC, backmeupplz commented on src/models/Subscription.ts
> +    chatId,
Надо, наверное, и по userId тоже искать?

2021-07-23 16:43 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +      ctx.reply(ctx.i18n.t('start_group_admin'))
Не стоит терять `await` в функциях, которые возвращают промисы.

2021-07-23 16:43 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +      const subscription = await getOrCreateSubscription(
Здесь не нужно создавать подписку, сюда можем зайти только для конфигурации группы адмнистратором группы

2021-07-23 16:43 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  const subscription = await getOrCreateSubscription(ctx.from.id, ctx.chat.id)
`ctx.from.id` и `ctx.chat.id` тут будут одинаковыми, ведь это в личке :) тебе нужно из `startPayload` получать id группы, на которую хочет подписаться пользователь, если хочешь показать ему тут подписку. `startPayload` — это часть ссылки после `?start=`, например: `https://t.me/paid_subscription_bot?start=12345`

2021-07-24 10:01 UTC, fanamoner commented on src/models/Subscription.ts
> +    chatId,
Если пользователь, который не является админом, будет получать подписку то будет ошибка, ведь подписка создается с `userId` админа. Я подумал, что после создания можно искать просто по `chatId`.

2021-07-25 18:21 UTC, backmeupplz requested changes

2021-07-25 18:21 UTC, backmeupplz commented on src/models/Subscription.ts
> +@modelOptions(typegooseOptions)
А почему глобально всем моделям не сделать эти опции? Так же и было раньше

2021-07-25 18:21 UTC, backmeupplz commented on src/handlers/handleStart.ts
> -
кажется, лишнее изменение

2021-07-25 18:21 UTC, backmeupplz commented on src/handlers/handleStart.ts
>      const userId = +ctx.from.id
Хм, тут же не нужен +, вроде как. Это уже number

2021-07-26 09:24 UTC, fanamoner commented on src/models/Subscription.ts
> +@modelOptions(typegooseOptions)
Оно не будет работать. Нужно, чтобы `setGlobalOptoions` применялись перед созданием всех моделей, а если они в отдельном файле, то придется в каждый файл вставлять `setGlobalOptoions`, как я понял. Смотрел [здесь](https://github.com/typegoose/typegoose/issues/128)

2021-07-31 00:01 UTC, backmeupplz requested changes

2021-07-31 00:01 UTC, backmeupplz commented on src/models/Subscription.ts
> +@modelOptions(typegooseOptions)
Окей. Попробуй сделать это не в `models/index`, а прямо в `app.ts:7` объявить глобальные опции. Если не получится и все равно нужно будет создавать `typegooseOptions`, то вынеси их в отдельный файл в хелперах

2021-07-31 00:01 UTC, backmeupplz commented on src/models/Subscription.ts
> +  chatId: number | string
Тут нужно принимать только `number`

2021-07-31 00:01 UTC, backmeupplz commented on src/models/Subscription.ts
> +  const chat = await ChatModel.findOne({ id: chatId })
А если такого чата нет?

2021-07-31 00:01 UTC, backmeupplz commented on src/models/Subscription.ts
> +  chatId: number | string
Делаем только `number`

2021-07-31 00:01 UTC, backmeupplz commented on src/models/Subscription.ts
> +export class Subscription {
Добавь `{ index: true }` в `userId`, `chatId`, `chat`. Посмотри, что такое индексация в монго.

2021-07-31 00:01 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  const subscription = await getOrCreateSubscription(ctx.from.id, startPayload)
А что, если `startPayload` — `''`? Тогда нужно прислать просто `help`.

2021-07-31 00:01 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +      subscriptionPrice: subscription.chat.price.monthly.eth,
Что, если `price` все еще не указан у чата?

2021-08-02 16:17 UTC, backmeupplz requested changes

2021-08-02 16:17 UTC, backmeupplz commented on src/helpers/typegoose.ts
> +}
А можем вычленить тип конфига из `typegoose`, чтобы получить тут автокомплит? И сделать `as TypegooseOptions` или что-то типа того

2021-08-02 16:17 UTC, backmeupplz commented on src/models/Chat.ts
> +import { typegooseOptions } from '@/helpers/typegoose'
Давай-ка назовем файл `typegooseOptions`

2021-08-02 16:17 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  if (startPayload === '') {
Это можно заменить на `!startPayload`

2021-08-02 16:17 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +    Number(startPayload)
Это можно заменить на `+startPayload`

2021-08-02 16:17 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  const subscription = await getOrCreateSubscription(
Что, если у нас появятся новые типы `startPayload` позже? Сделай проверку на то, какой это пейлоад. Вроде как, должны быть только отрицательные цифры, используй regex

2021-08-02 16:17 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  if (startPayload === '') {
Если ты тут проверяешь на отсутствие пейлоада, то после этого не нужно проверять его наличие

2021-08-03 10:31 UTC, fanamoner commented on src/helpers/typegoose.ts
> +}
Попробовал. Взял интерфейсы из [репозитория typegoose](https://github.com/typegoose/typegoose/blob/master/src/types.ts#L385).

2021-08-03 22:08 UTC, backmeupplz requested changes

2021-08-03 22:08 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  if (startPayload.match(/^-?\d+$/)) {
А подписываться же мы только на группы и каналы можем? Скорее всего, всегда будет отрицательный тогда id

2021-08-03 22:08 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +    if (subscription.chat.price) {
Давай сначала проверим `!subscription.chat.price`, а потом закинем вариант без ошибок. Сначала нужно ошибки проверять (типа отсутствия цены), потом в конце подходить к happy path

2021-08-03 22:08 UTC, backmeupplz commented on src/helpers/typegooseOptions.ts
> +interface TypegooseOptions {
Нет смысла самим прописывать объект, который съедает `@modelOptions`. Используй `IModelOptions` от typegoose

2021-08-04 16:59 UTC, merged