Add configure subscription
Borodutch/paid_subscription_bot pull request #5
Opened 2021-08-11 07:56 UTC by moody-cookie

2021-08-11 23:51 UTC, backmeupplz requested changes

2021-08-11 23:51 UTC, backmeupplz commented on src/models/Subscription.ts
> -interface Accounts {
Нам точно не нужны эти модели?

2021-08-11 23:51 UTC, backmeupplz commented on src/models/Chat.ts
> +      console.log(chat)
Давай лишние console.log не добавлять в PR

2021-08-11 23:51 UTC, backmeupplz commented on src/models/Chat.ts
> +  accounts?: Accounts
У каждой подписки свой кошелек. У каждого канала свой кошелек. Люди, переведя деньги на кошелек подписки (уникальный для каждого челоека), ожидают, что деньги с кошелька подписки уйдут на общий кошелек канала + в подписке останется об этом заметка

2021-08-11 23:51 UTC, backmeupplz commented on src/models/Chat.ts
> +  accounts?: Accounts
При конфигурации канала не нужно указывать приватный ключ

2021-08-11 23:51 UTC, backmeupplz commented on locales/ru.yaml
> +configure_subscriptions: |
Давай в `en` тоже добавим строки

2021-08-11 23:51 UTC, backmeupplz commented on locales/ru.yaml
> +  Выберите канал для настройки:
Если это просто 1 строка, нам не нужен |

2021-08-11 23:51 UTC, backmeupplz commented on locales/ru.yaml
> +  Private key: ${privateKey}
Приватный ключ тут не нужен

2021-08-11 23:51 UTC, backmeupplz commented on locales/ru.yaml
> +  Вы конфигурируете подписку на канал: ${chatId}
Помимо chat it, нужно показать хотя бы название канала

2021-08-12 17:07 UTC, backmeupplz requested changes

2021-08-12 17:07 UTC, backmeupplz commented on src/app.ts
> +bot.command('cancel', handleConfigureCancel)
Тут скорее можно сделать просто `handleCancel`, ведь не только в конфигурации подписки мы будем его использовать — но и во всех других функциях, основанных на стейте

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +import { web3 } from '../helpers/web3'
Давай использовать модульные импорты

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +import { sendConfigureSingleSubscription } from './handleConfigureSubscription'
Нужны модульные импорты

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +  console.log(subscription)
Не нужно пушить лишние `console.log`

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +    // if status not allowed, send back a denial
Давай не будем добавлять лишние комменты

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +
Ну и лишние строки давай не добавлять :)

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +      const chat = await findChat(chatId)
Он уже есть в `ctx.dbchat`

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +      chat.administratorIds = chat.administratorIds || []
Какой-то очень неприятный хак

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +  administratorIds?: number[]
Чтобы хака выше не было, сделай `{ required: true, default: [] }`

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleStart.ts
> +        chat.save(),
У тебя тут всего две операции, сделай простые await, не нужно делать `Promise.all`

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +  ethAddress?: string
Потом будем добавлять другие валюты, поэтому лучше использовать конструкцию из `Subscription`

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +// state of private chat for configuration of public paid chats
Лишний коммент

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +export enum ConfigurationState {
Просто назови это `State`. В будущем у нас могут быть и другие стейты

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +  @prop({ default: ConfigurationState.none })
Тут можно прописать `enum: `

2021-08-12 17:07 UTC, backmeupplz commented on src/models/Chat.ts
> +  configuredChat?: number
Это случайно не `configuredChatId`?

2021-08-12 17:07 UTC, backmeupplz commented on locales/ru.yaml
> +configure_cancel: Настройка подписки отменена.
Можно просто сделать `Действие отменено`, в будущем `/cancel` мы можем использовать с другими командами тоже

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +  if (!('text' in ctx.message)) return
Не используй короткую запись без `{}`, пожалуйста

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +  if (!('text' in ctx.message)) return
Если хочешь обойтись без магических строк (а к этому всегда нужно стремиться), замени на `if (!ctx.message?.text)`

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +  const message = ctx.message
смысла нет уменьшать длину на 4 символа

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +  // fetch chat name
Лишний коммент

2021-08-12 17:07 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +    configuredChannel.configurationState ===
Со стейтами лучше делать switch и выносить хендлеры каждого стейта в отдельные функции

2021-08-15 05:30 UTC, moody-cookie commented on src/handlers/handleStart.ts
> +      const chat = await findChat(chatId)
В dbchat лежит приватный чат (переписка админа и бота).
Поиск выполняется для конфигурируемого чата, которому и приписываются админы.
Переименую переменную, чтобы было более чётко.

2021-08-15 05:43 UTC, moody-cookie commented on src/handlers/handleConfigureSubscription.ts
> +  if (!('text' in ctx.message)) return
TS выдает ошибку на такое действие: 
[Скрин](https://i.imgur.com/882KVgO.png)

2021-08-17 01:19 UTC, backmeupplz requested changes

2021-08-17 01:19 UTC, backmeupplz commented on src/app.ts
> +// Errorsprettierprettierprettier
Тут что-то не то

2021-08-17 01:19 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +  configuredChannel.accounts = configuredChannel.accounts || {}
Давай от этих хаков избавляться

2021-08-17 01:19 UTC, backmeupplz commented on src/models/Accounts.ts
> +export interface Accounts {
Тут можно сделать class и прописать @prop, как в доках typegoose

2021-08-17 01:19 UTC, backmeupplz commented on src/models/Chat.ts
> +  administratorIds?: number[]
Он теперь всегда будет существовать, не нужно у `required: true` добавлять `?`

2021-08-24 01:16 UTC, backmeupplz requested changes

2021-08-24 01:16 UTC, backmeupplz commented on src/models/Chat.ts
> +
Давай не будем добавлять лишние строки

2021-08-24 01:16 UTC, backmeupplz commented on src/models/Chat.ts
> +  @prop({ _id: false, default: { monthly: { eth: NaN } } })
Вместо `NaN` просто сделай `price` опциональным. Пускай будет пустым, пока админ его не настроит

2021-08-24 01:16 UTC, backmeupplz commented on src/models/Chat.ts
> +  @prop({ _id: false, default: { eth: { address: '', privateKey: '' } } })
Вместо пустых значений, сделай это поле тоже опциональным

2021-08-24 01:16 UTC, backmeupplz commented on src/models/Chat.ts
> +  walletConfigureMessageId?: number
А мы это используем? Если нет, нужно убрать

2021-08-24 01:16 UTC, backmeupplz commented on src/models/Chat.ts
> +  paymentConfigureMessageId?: number
А мы это используем? Если нет, нужно убрать

2021-08-24 01:16 UTC, backmeupplz commented on src/models/Accounts.ts
> +    address: string
Не нужно вот это в отдельный класс убирать? Сохраняется норм?

2021-08-24 01:16 UTC, backmeupplz commented on locales/ru.yaml
> +  Дайте потенциальным участникам группы <a href="https://t.me/${botName}?start=${chatId}">эту ссылку</a>, чтобы они могли подписаться.
Можно ссылку без тега `a` делать, просто плейнтекстом — ее же копировать будут

2021-08-24 01:16 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +export const handleCancel = async (ctx: Context) => {
Это можно даже в отдельный файл вынести

2021-08-24 01:16 UTC, backmeupplz commented on src/handlers/handleConfigureSubscription.ts
> +export const handleConfigureMessage = async (ctx: Context) => {
И это тоже можно в отдельный файл вынести

2021-08-24 01:16 UTC, backmeupplz commented on src/app.ts
> +bot.on('message', handleConfigureMessage)
Может, нужно и тут `stopIfPublic`?

2021-09-20 01:56 UTC, merged